server:
  port: 8100
  context-path: /provider
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@10.1.167.125:1521:xe
    username: demo
    password: demo
logging:
  level: info